--ALTER TABLE HELLO_LOGIN DROP CONSTRAINT HELLO_LOGIN_PK
--GO
DROP TABLE HELLO_LOGIN
GO
CREATE TABLE HELLO_LOGIN (
		userID VARCHAR(24) NOT NULL,
		userPW VARCHAR(24) NOT NULL
	)
GO
ALTER TABLE HELLO_LOGIN ADD CONSTRAINT HELLO_LOGIN_PK PRIMARY KEY (userID)
GO